server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  datasource:
    url: jdbc:mysql://localhost:3306/lol
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.MySQL8Dialect

service.mock: true
STRIPE: ""
BUCKET: radit-bucket-dev
S3: http://localhost:4566/

jwt:
  secret: VerySecureLol
PASSWORD: password

