server:
  port: 8080

BUCKET: radit-bucket

spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.MySQL8Dialect